---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost
spec:
  online: true
  bmc:
    ip: 192.168.100.100
    credentialsName: bmc1-secret
